# Generated by Django 6.1.1 on 2026-09-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('point_1_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('point_1_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('point_2_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('point_2_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('point_3_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('point_3_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('point_4_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('point_4_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
