# Generated by Django 6.1.1 on 2026-09-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='point_1_lat',
        ),
        migrations.RemoveField(
            model_name='location',
            name='point_1_lng',
        ),
        migrations.RemoveField(
            model_name='location',
            name='point_2_lat',
        ),
        migrations.RemoveField(
            model_name='location',
            name='point_2_lng',
        ),
        migrations.RemoveField(
            model_name='location',
            name='point_3_lat',
        ),
        migrations.RemoveField(
            model_name='location',
            name='point_3_lng',
        ),
        migrations.RemoveField(
            model_name='location',
            name='point_4_lat',
        ),
        migrations.RemoveField(
            model_name='location',
            name='point_4_lng',
        ),
        migrations.AddField(
            model_name='location',
            name='point_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='point_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='point_3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='point_4',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
