# Generated by Django 6.1.1 on 2026-09-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_location_point_1_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
