# Generated by Django 6.1.1 on 2026-09-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_group_created_at_alter_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='shift',
            field=models.PositiveSmallIntegerField(choices=[(1, '1-smena'), (2, '2-smena')], default=1),
        ),
    ]
